// Generated by CoffeeScript 1.6.2
(function() {
  describe("Binary property based on typed array", function() {
    it("Module 'jA' is defined", function() {
      return expect(jA).toBeDefined();
    });
    return describe("Binary property", function() {
      var A, B;

      A = jA.binary();
      B = jA.binary();
      it("Create two binary properties 'A' and 'B'", function() {
        expect(A).toBeDefined();
        return expect(B).toBeDefined();
      });
      it("Add 20 elements to  'A'", function() {
        A.add(20);
        return expect(A.length).toBe(20);
      });
      it("Add 1 elements to property 'A' with value 'true'", function() {
        A.add(1, true);
        return expect(A.get(20)).toBe(true);
      });
      it("Property 5th element of 'A' with value 'true'", function() {
        A.set(5, true);
        return expect(A.get(5)).toBe(true);
      });
      it("Elements with index other then 5 and 20 are 'false'", function() {
        var n, _results;

        n = A.length;
        _results = [];
        while (n--) {
          switch (n) {
            case 5:
            case 20:
              _results.push(expect(A.get(n)).toBe(true));
              break;
            default:
              _results.push(expect(A.get(n)).toBe(false));
          }
        }
        return _results;
      });
      it("Property 'B' has no elements", function() {
        return expect(B.length).toBe(0);
      });
      return it("Property 'A' has 6 elements when 15 are deleted", function() {
        A.add(-15);
        expect(A.length).toBe(6);
        expect(A.get(5)).toBe(true);
        return expect(A.get(4)).toBe(false);
      });
    });
  });

}).call(this);
